### ISSUE TITLE
Xbox Control

### ISSUE THREAD

**Issue by sxj754** [cwruRobotics/rov-23#36]
Write a node that monitors Xbox controller input in the main RQT window (not just one of our plugins) and then sends the appropriate command velocities down the tether.

See [#11](https://github.com/cwruRobotics/rov-23/issues/11).

**Comment by InvincibleRMC** [comment]
@benjaminwp18 Should the Joystick controls be sent to the task requester and then have the task requester send the command velocities down the tether? Then presumably #14 will subscribe on the pi.

**Comment by NoahMollerstuen** [comment]
I think the task action server node should subscribe to the controller inputs and publish target "efforts" in each of the 6 axes

**Comment by InvincibleRMC** [comment]
Custom service with x,y,z and pitch,yaw,roll

**Comment by benjaminwp18** [comment]
Duplicating discord stuff: the Xbox controller node should talk directly down the tether to the Pi; task requester should just deal with starting/stopping/receiving feedback from tasks, not task-specific data.
