### ISSUE TITLE
Operator GUI

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-23#38]
Create second GUI with separate `surface_main` launch file for operator laptop. Move already created GUI modules & backend stuff to the second launch where appropriate.

Decide whether operator will switch tasks for _every_ task (e.g. taking a picture of the seagrass habitat), or whether they'll have access to general buttons for recording images/videos for later viewing. See the software column of the [task list](https://docs.google.com/spreadsheets/d/1OQpF9YHQ2OBLLKuip4RsIXiebvILBrW31Eu4gBnE0AU/edit) for tasks where we'll do something besides manual control.

Other tickets will be responsible for creating task-specific operator GUI features.

**Comment by InvincibleRMC** [comment]
#58 @benjaminwp18  close?

**Comment by benjaminwp18** [comment]
@InvincibleRMC We should talk about how/when operator will switch tasks, either in-person or on Discord before closing this
