### ISSUE TITLE
GUI beautification & dark mode

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-23#39]
Create a dark theme & watermelon theme which can be selected by command line argument on launcher.

Make the GUI a bit prettier/better proportioned; see last year's GUI:
![Image](https://user-images.githubusercontent.com/90342856/215599294-a3a9dd1a-3891-4d3a-88ea-7ef0e8869089.png)

**Comment by InvincibleRMC** [comment]
https://doc.qt.io/qtforpython/overviews/stylesheet-examples.html
