### ISSUE TITLE
Update thruster & manipulator controls

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-23#59]
Update thruster control mappings to:
- Match driver preferences (talk to Noah about the scheme we used last year; consider manipulator/¿cam switching? controls too)
- Actually control the correct thrusters (test on ROV)

**Comment by InvincibleRMC** [comment]
Currently rov_msg.yaw and rov_msg.y are swapped

**Comment by InvincibleRMC** [comment]
3 cardinal directions were tested. The rotatey ones work not sure if they spin the right way though
