### ISSUE TITLE
Image stream display improvements

### ISSUE THREAD

**Issue by benjaminwp18** [cwruRobotics/rov-23#60]
- Make image stream widgets resize dynamically
- Fix [ros2_video_streamer](https://github.com/cwruRobotics/ros2_video_streamer) to stream in correct color profile. Right now streamed files need to have their frames converted with this in `video_area.py`:
     ```python
      # Rectify weird colors
     cv_img = cv2.cvtColor(cv_img, cv2.COLOR_RGB2RGBA)
     ```
     Which is bad because that screws up real camera stream colors.
     **Michael's fixing this**
- Look into streaming the binary for cv images directly, rather than using ROS images

**Comment by InvincibleRMC** [comment]
If @benjaminwp18 wants to look into proper ROS Video stuff see http://wiki.ros.org/image_transport. However, For some reason, it is still only c++ so yeah :/

**Comment by benjaminwp18** [comment]
Use symlinks
